### ISSUE TITLE
In non-interactive use all diagnostics messages are suppressed

### ISSUE THREAD

**Issue by doublep** [mattiase/trawl#10]
Only the totals are printed:

    emacs --batch --exec "(progn (package-initialize) (require 'relint) (relint-file \"project-b.el\"))"
    relint: 1 error.

I believe this is a regression, vaguely remember that it used to work non-interactively too.

**Comment by mattiase** [comment]
`relint-file`, `relint-directory` and `relint-current-buffer` output to the `*relint*` buffer since they are intended for interactive use. You are probably looking for `relint-batch` which is made for non interactive use:

`emacs -batch -f package-initialize -l relint -f relint-batch files-and-directories...`

For example, to check all elisp files in `mydir` using all your 128 CPU cores:

`find mydir -name '*.el' -type f|xargs -P128 emacs -batch -f package-initialize -l relint -f relint-batch`

**Comment by doublep** [comment]
> relint-file, relint-directory and relint-current-buffer output to the *relint* buffer since they are intended for interactive use.

I now checked, at least `relint-file` worked also in non-interactive mode in version 1.14:

    ~/eldev/test/project-b$ eldev -S "(eldev-use-local-dependency \"~/git/relint\")" lint re
    project-b.el:23:19: In call to string-match-p: Error: Missing \): "^\\(.)$"
    relint: 1 error.

In comparison, when I check out 1.15 (or anything later) in `~/git/relint`, I get this:

    ~/eldev/test/project-b$ eldev -S "(eldev-use-local-dependency \"~/git/relint\")" lint re
    relint: 1 error.

So, it is a regression in 1.15, even if it was done intentionally.

>You are probably looking for relint-batch which is made for non interactive use

Not really. I can't use it because 1) it works on the files it finds itself, while I have a list of file to work on, i.e. not necessarily all files in the directory; 2) it kills Emacs, while I need to continue after relint has finished its work, e.g. run other linters.

**Comment by doublep** [comment]
I can locally restore the old behavior by putting the body of `relint--get-error-buffer` into `(unless noninteractive ...)`. Would it be possible to just commit such a change? Then most relint functions also work in non-interactive mode.

**Comment by mattiase** [comment]
Thank you – while it could be useful to have the same behaviour in interactive and non-interactive mode (for scripts that want to do something with the errors in the buffer, for instance), it's probably more useful to let it go to stderr. There is always `relint-buffer` for full programmatic control.
