### ISSUE TITLE
Error running relint: Required package ‘xr-1.22’ is unavailable

### ISSUE THREAD

**Issue by ideasman42** [mattiase/trawl#12]
This message is showing up on startup:
```
Unable to activate package ‘relint’.
Required package ‘xr-1.22’ is unavailable
```

xr is now at version 1.23.

**Comment by mattiase** [comment]
That's odd – I cannot reproduce that with Emacs 28.2 after installing xr 1.23 and relint 1.20.
Are there any other messages preceding those you quoted?
What Emacs version are you running?
If you temporarily move your `.emacs`, `.emacs.d` etc away, start from a clean slate and install just those packages from GNU ELPA, do you get the same error?

**Comment by ideasman42** [comment]
Deleted my `~/.config/emacs/elpa` directory and re-downloading all packages resolved this issue. I'm building emacs from master, perhaps this caused the issue.

Sorry for the noise.

**Comment by mattiase** [comment]
Good to hear about the quick resolution!
