### ISSUE TITLE
Relint on current buffer

### ISSUE THREAD

**Issue by manuel-uberti** [mattiase/trawl#5]
Hi,

first of all thanks for this great package.

This is more of a feature request than an issue reporting. Is it possible to have `relint-file` running on the current buffer instead of having it prompt for a file to choose?

**Comment by mattiase** [comment]
A very reasonable request! Right now, relint relies on compilation-mode to couple errors to position in the elisp file. If there is no file, or if the buffer contains unsaved changes, then that no longer works and a different solution is needed. I'll see what can be done.

**Comment by manuel-uberti** [comment]
Thank you for the add. I'll report back if I encounter any problems.
