### ISSUE TITLE
Batch mode with exit status

### ISSUE THREAD

**Issue by DamienCassou** [mattiase/trawl#6]
Hi,

would you mind changing the `relint-batch` function to call `(kill-emacs 0)` when there is no problem found and `(kill-emacs 1)` when there is at least one? It would ease implementation of Emacs lisp checking tools such as https://github.com/alphapapa/makem.sh.

Thanks

**Comment by mattiase** [comment]
Not at all. Thanks for the suggestion!

**Comment by DamienCassou** [comment]
Thank you, that was quick!

**Comment by alphapapa** [comment]
@mattiase Thanks!  There is one more small issue: https://github.com/alphapapa/makem.sh/issues/8#issuecomment-577923844  Would you be willing to make that adjustment in relint as well?

**Comment by mattiase** [comment]
Certainly, that is reasonable behaviour. Done.

**Comment by alphapapa** [comment]
Thanks!

**Comment by alphapapa** [comment]
@mattiase Forgive my impatience, but I just realized that this package is in ELPA rather than MELPA, and the version in ELPA hasn't received this fix yet.  Will the new version make it into ELPA soon?

**Comment by mattiase** [comment]
Sorry about the delay; there were some pending improvements awaiting integration. I have now updated xr and relint and pushed them to ELPA.

**Comment by alphapapa** [comment]
Thanks.  Also, I didn't realize that you are also the author of `xr`.  Let me express my gratitude for your work on it as well!

**Comment by mattiase** [comment]
You're welcome!
