### ISSUE TITLE
Tests fail even on the current stable Emacs 26.3

### ISSUE THREAD

**Issue by doublep** [mattiase/trawl#7]
Looks like one of the issues is that tests depend on `flatten-tree`, which is new in 27.

I guess it would be helpful if you configured continuous integration.

**Comment by mattiase** [comment]
Thanks for the report! Given that 27 is stabilising for release, this particular problem is going to solve itself eventually, but there's no need to make it difficult for people to run the tests in the meantime. I disabled those that wouldn't run in Emacs 26.1 (which was the newest stable release at hand).

If this becomes more of a problem in the future, perhaps a mechanism that skips tests that depend on features not present in the running Emacs would be useful.

**Comment by doublep** [comment]
Maybe you should add some requirement on minimum Emacs version to `relint.el`. As it is now, I have no idea which Emacs version is really needed. It's not so much of a problem for personal use, but becomes problematic when you want to use `relint` from another tool.

**Comment by mattiase** [comment]
Wish granted, I already did! However, the test suite probably requires a more recent version. I suppose a Package-Requires: header could be added to relint-test.el, but I fear it would just confuse package management software.

**Comment by doublep** [comment]
> Wish granted, I already did!

I see you added Emacs 25.1 as a requirement . Unfortunately this is not enough, as `relint` needs at least 26.1 because it calls `mapcan`.

My interest comes from trying to integrate `relint` with [Eldev](https://github.com/doublep/eldev). I got to the point where it works fine with later Emacs versions, but fails in an ugly way on earlier versions.  E.g.:

    $ EMACS=emacs-25.3 eldev lint re
    Importing package-keyring.gpg...
    Importing package-keyring.gpg...done
    [1/2] Installing package ‘xr’ (1.14) from ‘gnu’...
    [2/2] Installing package ‘relint’ (1.12) from ‘gnu’...
    Symbol’s function definition is void: mapcan

I dislike such things because if anyone runs into it, they will certainly say: "Gah, Eldev sucks!" even though here the error is in `relint`.

It is fine for me whether you change the requirement to 26.1 or make sure `relint` actually *does* work on 25.1 as it promises. But I'm sure if you don't use some form of continuous integration this will get broken again in ten commits.

Would you accept a PR for using Travis CI? Would it be fine if this used Eldev (this doesn't make your package *depend* on Eldev, it's an infrastructure-only tool that doesn't affect package contents as e.g. published in ELPA)?

**Comment by mattiase** [comment]
Serves me right to trust whatever package I ran to come up with 25.1. (Looks like the package-lint data file was incomplete!) Raised to 26.1, both for relint and xr (which also uses mapcan). Thanks again for your diligence!

Your offer is very kind but I think it will be all right; I just didn't pay much attention to the Emacs version before, but will be sure to do so now.
