### ISSUE TITLE
Tests fail on Emacs 26 again

### ISSUE THREAD

**Issue by doublep** [mattiase/trawl#9]
With Emacs 27 and up everything works. On 26 one test fails, see below.

Once again I propose to set up continuous integration with either Travis CI or GitHub workflows. It won't affect your code or tests at all, only project infrastructure. I can create a PR if you are interested.

    paul@gonzo:~/git/relint$ EMACS=emacs-26.3 eldev test -B
    Running 14 tests (2020-05-09 14:55:24+0200)
       passed   1/14  relint-buffer
       passed   2/14  relint-check-file-1
       passed   3/14  relint-check-file-10
    Test relint-check-file-11 backtrace:
        [omitted]

    Test relint-check-file-11 condition:
        (ert-test-failed
         ((should
           (equal
            (relint-test--scan-file "test/11.elisp")
            (relint-test--read-file "test/11.expected")))
          :form
          (equal "11.elisp:7:23: Duplicated character `c' (pos 2)
      \"abc\"
       ..^
    11.elisp:7:26: Duplicated character `b'
    11.elisp:8:30: Single-character range `c-c' (pos 4)
      \"0-9ac-ceg-h3\"
       ....^
    11.elisp:8:34: Two-character range `g-h' (pos 8)
      \"0-9ac-ceg-h3\"
       ........^
    11.elisp:8:37: Character `3' included in range `0-9' (pos 11)
      \"0-9ac-ceg-h3\"
       ...........^
    11.elisp:9:25: Range `f-t' overlaps previous `a-m'
    11.elisp:9:37: Character `s' included in range `f-t' (pos 1)
      \"!s\"
       .^
    11.elisp:10:45: Duplicated class `space'
    11.elisp:11:21: Suspect range `)-+' (pos 4)
      \"0-9()-+\"
       ....^
    11.elisp:12:20: Suspect range `+-.' (pos 3)
      \"0-9+-.\"
       ...^
    11.elisp:15:20: Literal `-' not first or last (pos 3)
      \"A-F-K-T\"
       ...^
    11.elisp:16:19: In rx `regexp' form: Duplicated `1' inside character alternative (pos 2)
      \"[11]\"
       ..^
    11.elisp:17:18: In rx `regex' form: Duplicated `2' inside character alternative (pos 2)
      \"[22]\"
       ..^
    11.elisp:18:14: Duplicated character `3' (pos 1)
      \"33\"
       .^
    11.elisp:20:29: Duplicated character `A' (pos 1)
      \"AA\"
       .^
    11.elisp:22:23: Duplicated character `B' (pos 1)
      \"BB\"
       .^
    11.elisp:23:10: Duplicated character `C' (pos 1)
      \"CC\"
       .^
    11.elisp:24:11: Duplicated character `D' (pos 1)
      \"DD\"
       .^
    11.elisp:29:25: Character `\\177' included in range `\\000-\\177' (pos 0)
      \"\\177\"
       ^
    11.elisp:29:32: Character `\240' included in range `\200-\377' (pos 0)
      \"\240\"
       ^
    " "11.elisp:7:23: Duplicated character `c' (pos 2)
      \"abc\"
       ..^
    11.elisp:7:26: Duplicated character `b'
    11.elisp:8:30: Single-character range `c-c' (pos 4)
      \"0-9ac-ceg-h3\"
       ....^
    11.elisp:8:34: Two-character range `g-h' (pos 8)
      \"0-9ac-ceg-h3\"
       ........^
    11.elisp:8:37: Character `3' included in range `0-9' (pos 11)
      \"0-9ac-ceg-h3\"
       ...........^
    11.elisp:9:25: Range `f-t' overlaps previous `a-m'
    11.elisp:9:37: Character `s' included in range `f-t' (pos 1)
      \"!s\"
       .^
    11.elisp:10:45: Duplicated class `space'
    11.elisp:11:21: Suspect range `)-+' (pos 4)
      \"0-9()-+\"
       ....^
    11.elisp:12:20: Suspect range `+-.' (pos 3)
      \"0-9+-.\"
       ...^
    11.elisp:15:20: Literal `-' not first or last (pos 3)
      \"A-F-K-T\"
       ...^
    11.elisp:16:19: In rx `regexp' form: Duplicated `1' inside character alternative (pos 2)
      \"[11]\"
       ..^
    11.elisp:17:18: In rx `regex' form: Duplicated `2' inside character alternative (pos 2)
      \"[22]\"
       ..^
    11.elisp:18:14: Duplicated character `3' (pos 1)
      \"33\"
       .^
    11.elisp:20:29: Duplicated character `A' (pos 1)
      \"AA\"
       .^
    11.elisp:22:23: Duplicated character `B' (pos 1)
      \"BB\"
       .^
    11.elisp:23:10: Duplicated character `C' (pos 1)
      \"CC\"
       .^
    11.elisp:24:11: Duplicated character `D' (pos 1)
      \"DD\"
       .^
    11.elisp:29:25: Character `\\177' included in range `\\000-\\177' (pos 0)
      \"\\177\"
       ^
    11.elisp:29:32: Character `\\240' included in range `\\200-\\377' (pos 0)
      \"\\240\"
       ^
    ")
          :value nil :explanation
          (arrays-of-different-length 1400 1412 "11.elisp:7:23: Duplicated character `c' (pos 2)
      \"abc\"
       ..^
    11.elisp:7:26: Duplicated character `b'
    11.elisp:8:30: Single-character range `c-c' (pos 4)
      \"0-9ac-ceg-h3\"
       ....^
    11.elisp:8:34: Two-character range `g-h' (pos 8)
      \"0-9ac-ceg-h3\"
       ........^
    11.elisp:8:37: Character `3' included in range `0-9' (pos 11)
      \"0-9ac-ceg-h3\"
       ...........^
    11.elisp:9:25: Range `f-t' overlaps previous `a-m'
    11.elisp:9:37: Character `s' included in range `f-t' (pos 1)
      \"!s\"
       .^
    11.elisp:10:45: Duplicated class `space'
    11.elisp:11:21: Suspect range `)-+' (pos 4)
      \"0-9()-+\"
       ....^
    11.elisp:12:20: Suspect range `+-.' (pos 3)
      \"0-9+-.\"
       ...^
    11.elisp:15:20: Literal `-' not first or last (pos 3)
      \"A-F-K-T\"
       ...^
    11.elisp:16:19: In rx `regexp' form: Duplicated `1' inside character alternative (pos 2)
      \"[11]\"
       ..^
    11.elisp:17:18: In rx `regex' form: Duplicated `2' inside character alternative (pos 2)
      \"[22]\"
       ..^
    11.elisp:18:14: Duplicated character `3' (pos 1)
      \"33\"
       .^
    11.elisp:20:29: Duplicated character `A' (pos 1)
      \"AA\"
       .^
    11.elisp:22:23: Duplicated character `B' (pos 1)
      \"BB\"
       .^
    11.elisp:23:10: Duplicated character `C' (pos 1)
      \"CC\"
       .^
    11.elisp:24:11: Duplicated character `D' (pos 1)
      \"DD\"
       .^
    11.elisp:29:25: Character `\\177' included in range `\\000-\\177' (pos 0)
      \"\\177\"
       ^
    11.elisp:29:32: Character `\240' included in range `\200-\377' (pos 0)
      \"\240\"
       ^
    " "11.elisp:7:23: Duplicated character `c' (pos 2)
      \"abc\"
       ..^
    11.elisp:7:26: Duplicated character `b'
    11.elisp:8:30: Single-character range `c-c' (pos 4)
      \"0-9ac-ceg-h3\"
       ....^
    11.elisp:8:34: Two-character range `g-h' (pos 8)
      \"0-9ac-ceg-h3\"
       ........^
    11.elisp:8:37: Character `3' included in range `0-9' (pos 11)
      \"0-9ac-ceg-h3\"
       ...........^
    11.elisp:9:25: Range `f-t' overlaps previous `a-m'
    11.elisp:9:37: Character `s' included in range `f-t' (pos 1)
      \"!s\"
       .^
    11.elisp:10:45: Duplicated class `space'
    11.elisp:11:21: Suspect range `)-+' (pos 4)
      \"0-9()-+\"
       ....^
    11.elisp:12:20: Suspect range `+-.' (pos 3)
      \"0-9+-.\"
       ...^
    11.elisp:15:20: Literal `-' not first or last (pos 3)
      \"A-F-K-T\"
       ...^
    11.elisp:16:19: In rx `regexp' form: Duplicated `1' inside character alternative (pos 2)
      \"[11]\"
       ..^
    11.elisp:17:18: In rx `regex' form: Duplicated `2' inside character alternative (pos 2)
      \"[22]\"
       ..^
    11.elisp:18:14: Duplicated character `3' (pos 1)
      \"33\"
       .^
    11.elisp:20:29: Duplicated character `A' (pos 1)
      \"AA\"
       .^
    11.elisp:22:23: Duplicated character `B' (pos 1)
      \"BB\"
       .^
    11.elisp:23:10: Duplicated character `C' (pos 1)
      \"CC\"
       .^
    11.elisp:24:11: Duplicated character `D' (pos 1)
      \"DD\"
       .^
    11.elisp:29:25: Character `\\177' included in range `\\000-\\177' (pos 0)
      \"\\177\"
       ^
    11.elisp:29:32: Character `\\240' included in range `\\200-\\377' (pos 0)
      \"\\240\"
       ^
    " first-mismatch-at 1354)))
       FAILED   4/14  relint-check-file-11
       passed   5/14  relint-check-file-12
       passed   6/14  relint-check-file-2
       passed   7/14  relint-check-file-3
       passed   8/14  relint-check-file-4
       passed   9/14  relint-check-file-5
       passed  10/14  relint-check-file-6
       passed  11/14  relint-check-file-7
       passed  12/14  relint-check-file-8
       passed  13/14  relint-check-file-9
       passed  14/14  relint-find-pos

    Ran 14 tests, 13 results as expected, 1 unexpected (2020-05-09 14:55:24+0200)

    1 unexpected results:
       FAILED  relint-check-file-11

    1 test produced an unexpected result
    paul@gonzo:~/git/relint$

**Comment by mattiase** [comment]
Thanks for the report! Apparently victim of an rx bug that I fixed in Emacs 27 some time ago but obviously forgot all about.

Regarding the auto-testing, fair enough – I gave it a shot and miraculously it seems to work. Certainly not up to your seasoned standards, but perhaps not too shabby for the time spent.
Please tell me if you are happy with the changes and I'll push it to GNU ELPA.

**Comment by doublep** [comment]
Sure, fine as long as it works. I'd test on all stable releases, but 26.3 is the most important, of course.

**Comment by mattiase** [comment]
Thank you but it does feel a tad extravagant, doesn't it? (I did a quick look-around: some packages try to test on every minor version they can lay their hands on, while others are more discriminating and make do with major releases only.)

What I'd like is a go against emacs-27, but I suppose that will have to wait until it an actual release.

I'm wrapping it up then for a push to ELPA. Thanks again!
